version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '${MONGO_CUSTOM_PORT}:27017'
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redisDB:/data

volumes:
  mongodb:
  redisDB:
