version: '3'

networks:
  tinyurl-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    networks:
      - tinyurl-network
    ports:
      - '${MONGO_CUSTOM_PORT}:27017'
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    networks:
      - tinyurl-network
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redisDB:/data

  tinyurl:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: tinyurl
    networks:
      - tinyurl-network
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - redis


volumes:
  mongodb:
  redisDB:
